--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/Pen
projects:
  Pen:
    icon: "icon.png"
    path: ""
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0.0.0
      - src: jojoe77777/FormAPI/jojoe77777/libFormAPI
        version: ^0.0.0
...